# Generated by Django 5.2.16 on 2026-07-12 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stock_created_at_stock_updated_at'),
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='name',
        ),
        migrations.AddField(
            model_name='stock',
            name='material',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='materials.material'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.stock'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
