# Generated by Django 5.2.16 on 2026-07-12 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_external', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('name_internal', models.CharField(max_length=255, unique=True)),
                ('name_external', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sale_price_internal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price_external', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
