# Generated by Django 5.2.16 on 2026-07-12 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name_internal']},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='id_external',
            new_name='pdv_external',
        ),
    ]
