# Generated by Django 5.2.16 on 2026-07-12 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pdv_external',
            new_name='id_external',
        ),
    ]
